environment:
  matrix:
    - nodejs_version: LTS
      configuration: publish

  NPM_TOKEN:
    secure: lyc/Fqx6ERTjiCoQoZuEQURQuo+7UP0M1bQJW/HXa+zb8Ly6qRDTY7xci5HJGpUU    

install:
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ./build.cmd

after_build:
  - ps: ./after_build.ps1

cache:
  - node_modules -> package.json, package-lock.json

deploy_script:
  - ps: |
      if ($ENV:CONFIGURATION -eq "publish")
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm pack"
        iex "npm publish --access public"
      }
    on:
      branch: master  
  - ps: |
      if ($ENV:CONFIGURATION -eq "publish")
      {
        "@ritterim:registry=https://ritterim.myget.org/F/npm/npm/`r`n//ritterim.myget.org/F/npm/npm/:_authToken=`$`{MYGET_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm pack"
        iex "npm publish"
      }  
    on:
      branch: master