environment:
  matrix:
    - nodejs_version: STABLE
      configuration: publish
    - nodejs_version: LTS

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - ./build.cmd

after_build:
  - ps: ./after_build.ps1

cache:
  - node_modules -> package.json, package-lock.json

test_script:
  - npm run browser-visual-tests

artifacts:
  - path: ./styleguide.zip
    name: Styleguide
    type: Zip

deploy:
  - provider: Environment
    name: Azure App Service Zip (Development)
    artifact: Styleguide
    slot: staging
    app_name: rim-style-east-dev
    on:
      branch: master
      configuration: publish

after_deploy:
    - ps: |
        if ($ENV:CONFIGURATION -eq "publish")
        {
          "@ritterim:registry=https://ritterim.myget.org/F/npm/npm/`r`n//ritterim.myget.org/F/npm/npm/:_authToken=`$`{MYGET_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
          iex "npm pack"
          iex "npm publish"
        }
      on:
        branch: master
